# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: bindupool

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    versionSpec: "11"
    jdkArchitectureOption: 'x64'
    javaHomeOption: 'JDKVersion'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: AzureCLI@2
  displayName: Resourcegroup
  inputs:
    azureSubscription: 'Free Trial (456685a9-1f1c-4cf4-a4cd-0306d40d5f83)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az group create --name mytestrg --location eastasia'
- task: AzureCLI@2
  displayName: Vnet
  inputs:
    azureSubscription: 'Free Trial (456685a9-1f1c-4cf4-a4cd-0306d40d5f83)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az network vnet create -g mytestrg -n testvnet --address-prefix 10.0.0.0/16 \
          --subnet-name testsubnet --subnet-prefix 10.0.0.0/24
- task: AzureCLI@2
  displayName: PublicIP
  inputs:
    azureSubscription: 'Free Trial (456685a9-1f1c-4cf4-a4cd-0306d40d5f83)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az network public-ip create -g mytestrg -n testip --allocation-method Dynamic'
- task: AzureCLI@2
  displayName: Securitygroup
  inputs:
    azureSubscription: 'Free Trial (456685a9-1f1c-4cf4-a4cd-0306d40d5f83)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az network nsg create -g mytestrg -n testnsg'
- task: AzureCLI@2
  displayName: Nic
  inputs:
    azureSubscription: 'Free Trial (456685a9-1f1c-4cf4-a4cd-0306d40d5f83)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az network nic create -g mytestrg --vnet-name testvnet --subnet testsubnet -n testnic'
- task: AzureCLI@2
  displayName: NICconfig
  inputs:
    azureSubscription: 'Free Trial (456685a9-1f1c-4cf4-a4cd-0306d40d5f83)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az network nic ip-config create -g mytestrg -n testipConfig --nic-name testnic --make-primary'
- task: AzureCLI@2
  displayName: CreateVM
  inputs:
    azureSubscription: 'Free Trial (456685a9-1f1c-4cf4-a4cd-0306d40d5f83)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az vm create -n testvm -g mytestrg --image UbuntuLTS --public-ip-address testip --authentication-type password --admin-username demouser --admin-password Bindu@123456789'
